---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Configure and Install Clickhouse
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "{{ repo_click }}/clickhouse-client/clickhouse-client_{{ clickhouse_version }}_{{ ansible_architecture }}.deb"
            dest: "./clickhouse-client_{{ clickhouse_version }}.deb"
            mode: "0755"
          # with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "{{ repo_click }}/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_{{ ansible_architecture }}.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}.deb"
            mode: "0755"
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "{{ repo_click }}/clickhouse-server/cclickhouse-server_{{ clickhouse_version }}_{{ ansible_architecture }}.deb"
            dest: "./clickhouse-server_{{ clickhouse_version }}.deb"
            mode: "0755"
    - name: Install clickhouse packages
      ansible.builtin.dnf:
        name:
          - clickhouse-common-static_{{ clickhouse_version }}.deb
          - clickhouse-client_{{ clickhouse_version }}.deb
          - clickhouse-server_{{ clickhouse_version }}.deb
        state: present
      become: true
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
- name: Install Vector
  hosts: vector
  handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Configure and Install Vector
      block:
        - name: Get Vector distrib
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{ vector_release }}/vector_{{ vector_version }}_{{ ansible_architecture }}.deb"
            dest: "./vector_{{ vector_version }}_{{ ansible_architecture }}.deb"
            mode: "0755"
        - name: Install Vector packages
          become: true
          ansible.builtin.dnf:
            name: vector-{{ vector_version }}.{{ ansible_architecture }}.rpm
          notify: Start vector service
        - name: Copy config
          ansible.builtin.template:
            src: "{{ vector_template }}"
            dest: "{{ vector_config_file }}"
            mode: "0644"
          notify: Start Vector service
